export const assets = {
  home: {
    hero: {
      avatarSmile: require("@images/home/hero/hero-icon.webp"),
      dribble: require("@images/home/hero/dribble.webp"),
      github: require("@images/home/hero/github.webp"),
      instagram: require("@images/home/hero/instagram.webp"),
      linkedin: require("@images/home/hero/linkedin.webp"),
      quadrilateral: require("@images/home/hero/quadrilateral.webp"),
      triangle: require("@images/home/hero/triangle.webp"),
      twistedTorus: require("@images/home/hero/twisted-torus.webp"),
      zigZag: require("@images/home/hero/zig-zag.webp"),
    },
    letsConnect: {
      avatarBigSmile: require("@images/home/letsConnect/contact-icon.webp"),
      dribble: require("@images/home/letsConnect/dribble.webp"),
      whatsapp: require("@images/home/letsConnect/whatsapp-icon.webp"),
      github: require("@images/home/letsConnect/github.webp"),
      gmail: require("@images/home/letsConnect/gmail.webp"),
      instagram: require("@images/home/letsConnect/instagram.webp"),
      linkedin: require("@images/home/letsConnect/linkedin.webp"),
    },
    myLatestProject: {
      figma: require("@images/home/myLatestProject/figma.webp"),
      ai: require("@images/home/myLatestProject/ai-icon.webp"),
      dev: require("@images/home/myLatestProject/dev-icon.webp"),
      rocket: require("@images/home/myLatestProject/rocket.webp"),
      suitcase: require("@images/home/myLatestProject/suitcase.webp"),
      projects: {
        myVision: require("@images/home/myLatestProject/projects/myVision.webp"),
        luxRide: require("@images/home/myLatestProject/projects/luxRide.webp"),
        lumaAI: require("@images/home/myLatestProject/projects/lumaAI.webp"),
        eventussol: require("@images/home/myLatestProject/projects/eventussol.webp"),
        climateAI: require("@images/home/myLatestProject/projects/climateAI.webp"),
        myVoice: require("@images/home/myLatestProject/projects/audioApp.webp"),
        hexaWear: require("@images/home/myLatestProject/projects/hexaWear.webp"),
      },
    },
    quote: {
      bulb: require("@images/home/quote/bulb.webp"),
      heart: require("@images/home/quote/heart.webp"),
      paintKit: require("@images/home/quote/paint-kit.webp"),
      teaCup: require("@images/home/quote/tea-cup.webp"),
    },
    technologyStack: {
      expo: require("@images/home/technologyStack/expo.webp"),
      expressJs: require("@images/home/technologyStack/express-js.webp"),
      javascript: require("@images/home/technologyStack/javascript.webp"),
      laravel: require("@images/home/technologyStack/laravel.webp"),
      nextJs: require("@images/home/technologyStack/next-js.webp"),
      planetScale: require("@images/home/technologyStack/planet-scale.webp"),
      prisma: require("@images/home/technologyStack/prisma.webp"),
      reactJs: require("@images/home/technologyStack/react-js.webp"),
      reactNative: require("@images/home/technologyStack/react-native.webp"),
      tailwindCss: require("@images/home/technologyStack/tailwindcss.webp"),
      typescript: require("@images/home/technologyStack/typescript.webp"),
      java: require("@images/home/technologyStack/java.webp"),
      python: require("@images/home/technologyStack/python.webp"),
      vercel: require("@images/home/technologyStack/vercel.webp"),
      node: require("@images/home/technologyStack/node.webp"),
      mongo: require("@images/home/technologyStack/mongo.webp"),
      llm: require("@images/home/technologyStack/llm.webp"),
      ml: require("@images/home/technologyStack/ml.webp"),
      genai: require("@images/home/technologyStack/genai.webp"),
    },
  },
};
